### ISSUE TITLE
Feature Request: Mod Configurations

### ISSUE THREAD

**Issue by pureliumy** [PNCommand/dst-worldgen#1]
非常棒，感谢！恰好前段时间半自动化做了一遍这个工作，还是非常繁琐的。

现在没能解决的是如何读取Mod的配置项、默认值和可选项，主要是包含动态生成选项的Mod。

**Comment by yechentide** [comment]
感谢你的使用！
lua的功能还是有些不足，不然感觉会好写很多。
我在[另外的脚本](https://github.com/PNCommand/DSTServerManager/blob/c42ffb013cae3bd81941aede74c6f77b6d50d1cb/bin/editor/mod_manager.lua#L76)里面有试着读取Mod的配置，不知道会不会对你有帮助。

`动态生成选项的Mod`是什么？我玩的mod少。。。
不过我遇到过选项里面塞了table的mod,对于这种就得多写一些类型判断了。
太麻烦了所以开服脚本那边我就没修hh

**Comment by yechentide** [comment]
这个仓库是用来生成worldgenoveride.lua的，所以不会添加任何和mod相关的东西，抱歉啦

**Comment by yechentide** [comment]
时隔一年，我又开始开发这个小项目了😂
你希望的功能已经完成。
但是有部分Mod会给世界生成前的配置界面添加选项，
比如岛屿冒险，永不言弃等等，
我目前正在尝试提取这部分数据。

**Comment by pureliumy** [comment]
真棒。常规mod设置项提取我自己也实现啦，从modinfo文件里面解析，但是像你提到的岛屿冒险这种，还没有很好的思路。
